### ISSUE TITLE
Error: Unable to retrieve data after package introduction

### ISSUE THREAD

**Issue by litiansky** [EasyAbp/CacheManagement#19]
My project is a background API, version 4.2. After I introduced all packages, I implemented the Get method of/API /cache-management/cache-item, but there is the following error. Could you please help me?

---

`{
  "error": {
    "code": null,
    "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
    "details": null,
    "data": {
      "ActivatorChain": "EasyAbp.CacheManagement.CacheItems.CacheItemController -> EasyAbp.CacheManagement.CacheItems.CacheItemAppService"
    },
    "validationErrors": null
  }
}`

---

Log:
`2021-02-06 16:08:23.277 +08:00 [INF] Executing endpoint 'EasyAbp.CacheManagement.CacheItems.CacheItemController.GetListAsync (EasyAbp.CacheManagement.HttpApi)'
2021-02-06 16:08:23.304 +08:00 [INF] Route matched with {action = "GetList", controller = "CacheItem", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[EasyAbp.CacheManagement.CacheItems.Dtos.CacheItemDto]] GetListAsync(Volo.Abp.Application.Dtos.PagedAndSortedResultRequestDto) on controller EasyAbp.CacheManagement.CacheItems.CacheItemController (EasyAbp.CacheManagement.HttpApi).
2021-02-06 16:08:23.399 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "\u5BF9\u4E0D\u8D77,\u5728\u5904\u7406\u4F60\u7684\u8BF7\u6C42\u671F\u95F4,\u4EA7\u751F\u4E86\u4E00\u4E2A\u670D\u52A1\u5668\u5185\u90E8\u9519\u8BEF!",
  "details": null,
  "data": {
    "ActivatorChain": "EasyAbp.CacheManagement.CacheItems.CacheItemController -\u003E EasyAbp.CacheManagement.CacheItems.CacheItemAppService"
  },
  "validationErrors": null
}

2021-02-06 16:08:23.399 +08:00 [ERR] An exception was thrown while activating EasyAbp.CacheManagement.CacheItems.CacheItemController -> EasyAbp.CacheManagement.CacheItems.CacheItemAppService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating EasyAbp.CacheManagement.CacheItems.CacheItemController -> EasyAbp.CacheManagement.CacheItems.CacheItemAppService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'EasyAbp.CacheManagement.CacheItems.CacheItemAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'EasyAbp.CacheManagement.CacheItems.ICacheItemManager cacheItemManager' of constructor 'Void .ctor(EasyAbp.CacheManagement.CacheItems.ICacheItemManager, EasyAbp.CacheManagement.CacheItems.ICacheItemRepository)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetAllBindings(ConstructorBinder[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.<>c__DisplayClass8_0`3.<EnableInterfaceInterceptors>b__1(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-02-06 16:08:23.400 +08:00 [ERR] ---------- Exception Data ----------
ActivatorChain = EasyAbp.CacheManagement.CacheItems.CacheItemController -> EasyAbp.CacheManagement.CacheItems.CacheItemAppService`

**Comment by gdlcf88** [comment]
Can you post a complete error message?

**Comment by litiansky** [comment]
> Can you post a complete error message

I've just added local logging to the description

**Comment by gdlcf88** [comment]
Do you have the `EasyAbp.CacheManagement.StackExchangeRedis` module installed?

**Comment by litiansky** [comment]
> Do you have the `EasyAbp.CacheManagement.StackExchangeRedis` module installed?

I don't have this module installed and it's not mentioned in the documentation

**Comment by litiansky** [comment]
> > Do you have the `EasyAbp.CacheManagement.StackExchangeRedis` module installed?
> 
> I don't have this module installed and it's not mentioned in the documentation，where should I install it?
> In my host project AbpCachingStackExchangeRedisModule component has been installed

Just install the components you said and connect to Redis. Thank you
